/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BooleanControlRenderer: typeof import('./components/marketplace/renderers/BooleanControlRenderer.vue')['default']
    DeploymentProgress: typeof import('./components/marketplace/DeploymentProgress.vue')['default']
    DeploymentWizard: typeof import('./components/marketplace/DeploymentWizard.vue')['default']
    DynamicFormField: typeof import('./components/DynamicFormField.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    EnumControlRenderer: typeof import('./components/marketplace/renderers/EnumControlRenderer.vue')['default']
    NumberControlRenderer: typeof import('./components/marketplace/renderers/NumberControlRenderer.vue')['default']
    PasswordControlRenderer: typeof import('./components/marketplace/renderers/PasswordControlRenderer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplashScreen: typeof import('./components/SplashScreen.vue')['default']
    StackCard: typeof import('./components/marketplace/StackCard.vue')['default']
    StackDetailsModal: typeof import('./components/marketplace/StackDetailsModal.vue')['default']
    StackReviews: typeof import('./components/marketplace/StackReviews.vue')['default']
    StringControlRenderer: typeof import('./components/marketplace/renderers/StringControlRenderer.vue')['default']
    TargetSelector: typeof import('./components/marketplace/TargetSelector.vue')['default']
    TextAreaControlRenderer: typeof import('./components/marketplace/renderers/TextAreaControlRenderer.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
